version: '2'
services:
  web:
    image: registry.cn-huhehaote.aliyuncs.com/zlb_dockerhub/osm:service
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db:5432
  db:
    image: registry.cn-huhehaote.aliyuncs.com/zlb_dockerhub/osm:db_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: openstreetmap
      POSTGRES_HOST_AUTH_METHOD: trust